Fix FFM detection on Java 21 (and 20)
On Java versions pre-22 FFM does not work. So disable FFM on Java
versions prior to 22. Should have the side effect that we no longer need
to catch `NoSuchMethodError`.

Fixes https://github.com/ajalt/mordant/issues/278

Without this, running on Java 20 or 21 in an interactive console and
`--enable-native-access=ALL-UNNAMED` throws the following stacktrace:

```
java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.foreign.MemorySegment
 	at java.base/java.lang.Class.cast(Class.java:4067)
 	at java.base/java.lang.invoke.VarHandles.insertCoordinates(VarHandles.java:501)
 	at java.base/java.lang.invoke.MethodHandles.insertCoordinates(MethodHandles.java:8144)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.FfmLayoutsKt.varHandle(FfmLayouts.kt:133)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.FfmLayoutsKt$shortField$$inlined$scalarField$default$1$1.invoke(FfmLayouts.kt:84)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.FfmLayoutsKt$shortField$$inlined$scalarField$default$1$1.invoke(FfmLayouts.kt:81)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.StructAccessor$DefaultImpls.getValue(FfmLayouts.kt:117)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.MacosCLibrary$winsize.getValue(TerminalInterface.ffm.macos.kt:11)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.MacosCLibrary$winsize.getWs_col(TerminalInterface.ffm.macos.kt:22)
 	at com.github.ajalt.mordant.terminal.terminalinterface.ffm.TerminalInterfaceFfmMacos.getTerminalSize(TerminalInterface.ffm.macos.kt:89)
 	at com.github.ajalt.mordant.terminal.TerminalDetectionKt.detectSize(TerminalDetection.kt:217)
 	at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:81)
 	at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:60)
 	at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:49)
```